### PR TITLE
Add option to return double quoted strings or not.

### PR DESCRIPTION
**Pull request by mcdrummerman**
I've added the ability to pass in an option "quote": false that will cause the string that are returned to not be wrapped in double quotes.

### CODE REVIEW

**Comment by dougwilson** [comment]
An ETag must have the double quotes. Here is a copy of the ABNF definition of an ETag:
```
     ETag       = entity-tag

     entity-tag = [ weak ] opaque-tag
     weak       = %x57.2F ; "W/", case-sensitive
     opaque-tag = DQUOTE *etagc DQUOTE
     etagc      = %x21 / %x23-7E / obs-text
                ; VCHAR except double quotes, plus obs-text
```

**Comment by dougwilson** [comment]
Sourced from https://tools.ietf.org/html/rfc7232#section-2.3

**Comment by mcdrummerman** [comment]
It needs one when sent in the header value but it would be nice to able to exclude them if saving the eTag somewhere, say a database or on a JS object

**Comment by dougwilson** [comment]
Can you provide a link to the standard for how to do that? The module states in the description is it RFC 7232 ETag values. We can generate another standard as well, what is the link?

**Comment by mcdrummerman** [comment]
Thanks. If it is strictly for RFC 7132 ETag values then I understand. 
I'm using it to create ETag strings and don't need the surrounding quotes.

**Comment by dougwilson** [comment]
But how you would ever re-quote the values? For example, the strong tag `"W/foo"` would be `W/foo` when it's unquoted, but so is `W/"foo"`. How would you know which form to re-quote as?

**Comment by mcdrummerman** [comment]
Good point. I think it's fair to close this and move on. Thanks for the discussion.

**Pull request closed without merging**
