### PR TITLE
Replace travis ci with github ci action

### PR DESCRIPTION
**Pull request by carpasse**
Asked whether it is ok to migrate to GH actions in https://github.com/expressjs/discussions/issues/229
If we do migrate. I imagine we will need to remove the project from [travis](https://app.travis-ci.com/github/jshttp/etag)

The new ci action  and README.md changes are based on the respective files in [cookie](https://github.com/jshttp/cookie) repository

### CODE REVIEW

**Comment by carpasse** [comment]
Action passing https://github.com/carpasse/etag/actions/runs/8733021909/job/23960944554

**Review by UlisesGascon — APPROVED** [review]
LGTM! Thanks for doing this migration @carpasse!

**Comment by UlisesGascon** [comment]
I am wondering why the CI has not being triggered in the PR :thinking:

**Comment by carpasse** [comment]
no idea 🙃

**Comment by UlisesGascon** [comment]
>  I am wondering why the CI has not being triggered in the PR 🤔

Maybe is because Github actions are not yet added to the principal branch, so the execution is ignored. I will have a look once is merged.

**Comment by UlisesGascon** [comment]
The CI is working as expected :partying_face: 

See: https://github.com/jshttp/etag/actions/runs/8874711397

**Pull request merged**
